jobs:
  build:
    docker:
      - image: danhatesnumbers/xelatex
    steps:
      - checkout
      - run:
          name: Build PDF
          command: make
      - store_artefacts:
          path: CV.pdf